### ISSUE TITLE
Is the current master branch working?

### ISSUE THREAD

**Issue by zoom2madan** [zheng4uga/AEM-GraphQL#1]
Hi

I tried to install the application on AEM 6.5. I successfully installed the bundle. Verified that the bundle is Active. Servlet is also Active

However, when i try to invoke the graphql servlet endpoint using

ENDPOINT:
http://localhost:4504/services/graphql/resource

QUERY using GraphiQL:
query {
 resource(resourcePath:"/content/we-retail/us/en"){
   title
 }
}

I get a TypeError: Failed to fetch error

Can you please advise, if the master branch build is working fine?

Thanks and Regards
Gaurav Madan

**Comment by zheng4uga** [comment]
fixed your issue and it is pushed to master. Also added a black/white strategy for graphql properties, and also added single point servlet entry
