### ISSUE TITLE
Error in buliding graphql rootBuilder

### ISSUE THREAD

**Issue by krvivek007** [zheng4uga/AEM-GraphQL#2]
Hi @zheng4uga ,

  Thanks for posting this code.
  I was trying to integrate this code in AEM then I got below error.
  {code} 
     Caused by: graphql.AssertException: Name must be non-null, non-empty and match [_A-Za-z][_0-9A-Za-z]*
  {code}
  This is coming as its trying to create field definition with name jcr:content and  : is not allowed as valid name. graphql.Assert#assertValidName().
   Could you please check and let me know if this is a valid issue and do we need to replace: whenever we are trying to add a name in fielddefinition.

Thanks,
Vivek Kumar

**Comment by zheng4uga** [comment]
It wouldnt allow : in the name. Just out of curiosity why would you use jcr:content as a field?

**Comment by zheng4uga** [comment]
fixed your issue and it's in master. Also added couple feature as black/white properties strategy, and added single entry servlet to handle query call.
