### ISSUE TITLE
Null while reading Unique child nodes

### ISSUE THREAD

**Issue by rsjoshi2912** [zheng4uga/AEM-GraphQL#7]
Hi,

One more thing I like to know related to the below query. I am trying to get values from the jcr:content node of the page. resourceGraphQl object is reading the node properly but while executing the query it is returning jcr_content as null. Is there anything that needed to be updated in the query?

"Jcr:created" is already allowed in the osgi config.
resourceGraphQLType have the "Jcr_content" data.

query : "{resource{jcr_created jcr_content{jcr_created}}}"

output :
{
    "errors": [],
    "data": {
        "resource": {
            "jcr_created": "2021-10-16T13:26:01.403+0530",
            "jcr_content": null
        }
    },
    "extensions": null,
    "dataPresent": true
}

**Comment by zheng4uga** [comment]
Hi,

Is there any error in the error log?

Thanks

**Comment by rsjoshi2912** [comment]
No Zheng. there is no error in logs or anywhere. Even I debug line to line and found that graphQL object has all jcr_content data in it but after executing the query it always returns null for any child node to the current node.

<img width="548" alt="Screenshot (147)" src="https://user-images.githubusercontent.com/27250129/138115438-05601601-e2c4-4085-8494-f3363a4ada07.png">

**Comment by rsjoshi2912** [comment]
Hi,

Silly me...It was a genuine mistake. I did not provide any check or implementation for the multi-valued properties. That's why I was getting a null pointer. 

Thanks,
Ravi Joshi
